#!/bin/bash
#SBATCH --export=SLURM_CPUS_PER_TASK,SLURM_JOB_NAME,SLURM_NTASKS_PER_NODE,SLURM_PRIO_PROCESS,SLURM_SUBMIT_DIR,SLURM_SUBMIT_HOST
#
#SBATCH --job-name=centiped
#SBATCH --mail-type=END
#SBATCH --mail-user=jbard@buffalo.edu
#
#SBATCH --output=output.out
#SBATCH --error=error.out
#
#SBATCH --time=01:30:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --partition=supporters

tstart=`date`
echo "###### start time: $tstart"

# spit out some basic SLURM information
echo "SLURM_JOBID         = "$SLURM_JOB_ID
echo "SLURM_JOB_NAME      = "$SLURM_JOB_NAME
echo "SLURM_SUBMIT_DIR    = "$SLURM_SUBMIT_DIR
echo "SLURM_NODELIST      = "`nodeset -e $SLURM_NODELIST`
echo "SLURM_NPROCS        = "$SLURM_NPROCS
echo "SLURM_NNODES        = "$SLURM_NNODES
echo "SLURM_CPUS_PER_TASK = "$SLURM_CPUS_PER_TASK
echo "SLURMTMPDIR         = "$SLURMTMPDIR
# retreiving user inputed information
while getopts j:c: option
do
	case "${option}"
	in
		j) JSON=${OPTARG};;
		c) CENTER=${OPTARG};;
	esac
done

# spit out user inputed information
echo "json = "$JSON
echo "center file  = "$CENTER
module load python/2.7.6
module load R/3.1.2
export R_LIBS_USER=~/R/x86_64-redhat-linux-gnu-library/3.0/
export PYTHONPATH=${PYTHONPATH}:/user/jbard/simplejson-3.6.5/:/user/jbard/numpy-1.9.1/build/lib.linux-x86_64-2.7/
# launch job
echo "Launching JOB . . ."


echo "Making Matrix . . ."
python makematrix.py $JSON $CENTER > $center.matrix.out

echo "Running Rscript . . ." 
Rscript runcent.R $center.matrix.out

echo "cleaning up . . ."
rm $center.matrix.out


# done
echo "All done! ;)"

tend=`date`
echo "###### end time: $tend"

